root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build] 
  args_bin = []
  bin = "tmp\\main.exe"
  cmd = "go build -o tmp/main.exe ./cmd/main.go"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata", ".vscode"]
  exclude_file = ["internal/config/app_config.go"]
  exclude_regex = ["_test.go", "app_config.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmp", "html"]
  include_file = [".env"]
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 1
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = true

[misc]
  clean_on_exit = false

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true
