.PHONY: test lint run
# Makefile for Go project

MODULE := $(shell grep ^module go.mod | awk '{print $$2}')

all: lint test run

test:
	@echo "🔍 Running unit tests..."
	@if [ -n "$(svc)" ]; then \
		richgo test -v ./test/unit/service/$(svc)_service_test.go; \
	else \
		richgo test -v ./test/...; \
	fi

lint:
	@echo "🧹 Running linter..."
	@golangci-lint run

run:
	@echo "🚀 Starting app..."
	@air

gen-service:
	go run tools/gen/gen_service.go --name $(name)
	@go fmt ./...
	@go mod tidy

remove-service:
	go run tools/remove/remove_service.go --name $(name)


gen-test:
	@echo "🧪 Generating service unit test for: $(name)"
	@mkdir -p ./test/unit/service
	@touch ./test/unit/service/$(shell echo $(name) | sed -E 's/(.*)Service/\L\1_service/')_test.go

	@echo "package service_test" > ./test/unit/service/$(shell echo $(name) | sed -E 's/(.*)Service/\L\1_service/')_test.go
	@echo '' >> ./test/unit/service/$(shell echo $(name) | sed -E 's/(.*)Service/\L\1_service/')_test.go
	@echo '// This is an autogenerated code' >> ./test/unit/service/$(shell echo $(name) | sed -E 's/(.*)Service/\L\1_service/')_test.go
	@echo 'import (' >> ./test/unit/service/$(shell echo $(name) | sed -E 's/(.*)Service/\L\1_service/')_test.go
	@echo '  "testing"' >> ./test/unit/service/$(shell echo $(name) | sed -E 's/(.*)Service/\L\1_service/')_test.go
	@echo '  "github.com/stretchr/testify/assert"' >> ./test/unit/service/$(shell echo $(name) | sed -E 's/(.*)Service/\L\1_service/')_test.go
	@echo '  mockrepo "github.com/msdevbytes/go-microkit/test/mocks/repository"' >> ./test/unit/service/$(shell echo $(name) | sed -E 's/(.*)Service/\L\1_service/')_test.go
	@echo '  "github.com/msdevbytes/go-microkit/internal/service"' >> ./test/unit/service/$(shell echo $(name) | sed -E 's/(.*)Service/\L\1_service/')_test.go
	@echo ')' >> ./test/unit/service/$(shell echo $(name) | sed -E 's/(.*)Service/\L\1_service/')_test.go
	@echo '' >> ./test/unit/service/$(shell echo $(name) | sed -E 's/(.*)Service/\L\1_service/')_test.go

	@echo 'func Test$(name)(t *testing.T) {' >> ./test/unit/service/$(shell echo $(name) | sed -E 's/(.*)Service/\L\1_service/')_test.go
	@echo '  repo := new(mockrepo.Mock$(shell echo $(name) | sed "s/Service//")Repository)' >> ./test/unit/service/$(shell echo $(name) | sed -E 's/(.*)Service/\L\1_service/')_test.go
	@echo '  svc := service.New$(name)(repo)' >> ./test/unit/service/$(shell echo $(name) | sed -E 's/(.*)Service/\L\1_service/')_test.go
	@echo '  assert.NotNil(t, svc)' >> ./test/unit/service/$(shell echo $(name) | sed -E 's/(.*)Service/\L\1_service/')_test.go
	@echo '}' >> ./test/unit/service/$(shell echo $(name) | sed -E 's/(.*)Service/\L\1_service/')_test.go

	@echo "✅ Unit test scaffold created for $(name)"

